# Generated by Django 4.2.2 on 2024-01-13 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newco', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_specification', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('people_applied', models.IntegerField(default=0)),
                ('applied', models.ManyToManyField(related_name='users_applied', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
