# Generated by Django 4.2.2 on 2024-03-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newco', '0007_alter_job_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_specification',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
