# Generated by Django 4.2.2 on 2024-03-09 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newco', '0010_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadharpdf',
            field=models.FileField(blank=True, null=True, upload_to='ssn', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
