# Generated by Django 4.2.2 on 2024-01-15 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newco', '0006_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='users_applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
