# Generated by Django 4.2.2 on 2024-03-09 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newco', '0011_userprofile_aadhar_userprofile_aadharpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pdfpsd',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aadharpdf',
            field=models.FileField(blank=True, null=True, upload_to='ssn/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
